DROP TABLE client IF EXISTS;

CREATE TABLE client (
    client_id bigint generated by default as identity,
    prenom VARCHAR(20),
    nom VARCHAR(20),
    CIN VARCHAR(20),
    numeroTierSiebel VARCHAR(20),
    employeur VARCHAR(20),
    montantCreance VARCHAR(20),
    nombreImpaye VARCHAR(20),
    ville VARCHAR(20),
    primary key (client_id )
);

CREATE TABLE telephone (
    telephone_id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    tel VARCHAR(20),
    typeTel VARCHAR(20),
    client_id INT,
      foreign key (client_id) references client(client_id)
);

CREATE TABLE adresse (
    adresse_id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    adresse VARCHAR(20),
    typeAdresse VARCHAR(20),
    client_id INT,
     foreign key (client_id) references client(client_id)
);


CREATE TABLE AffaireAmiable (
    affaireamiable_id BIGINT IDENTITY NOT NULL PRIMARY KEY ,
    numeroAffaire VARCHAR(20),
    creance VARCHAR(20),
    societeGestion VARCHAR(20),
    MontantImplaye VARCHAR(20),
    NombreImpaye VARCHAR(20),
    immatriculation VARCHAR(20),
    matricule VARCHAR(20),
    categorie VARCHAR(20),
    avancement VARCHAR(20),
    client_id INT,
      foreign key (client_id) references client(client_id)
);